### ISSUE TITLE
Could you provide your baseline model code?

### ISSUE THREAD

**Issue by Doragd** [ussaema/SeqCapsGAN#1]
Thanks for your awesome work ! It's so impressive~

I noticed that you used several baselines for comparison, such as SentiCap, RNN-Transfer, SeqCNNGAN. 

Can you easily give out the code of these baselines? 

Because the open source code of the community does not seem to have a unified pre-processing method 
and the code is also very difficult to understand.

Thank you again for your excellent work! I look forward to your reply.

**Comment by ussaema** [comment]
The score values of the baselines are copied from their papers. We are in fact interessted in inspecting the quality of the captions (which we could compute based on the language scores), without focusing on the steps performed by the baselines for the captions generation.
I don't know what do you exactly mean by pre-processing method. The pre-processing step performed in our work (for SeqCNNGAN and SeqCapsGAN) is to extract features from images using a pre-trained network + to project the captions onto the embedding space.

**Comment by Doragd** [comment]
thanks for your quick reply. 
My confusion is that on the task of stylized image caption, the division of senticap training and testing is as shown in the following figure, but they did not give the corresponding code. In fact, only part of the senticap data set has a complete 6 sentence positive and negative caption, and the rest of the data is not.
> Towards Generating Stylized Image Captions via Adversarial Training
![image](https://user-images.githubusercontent.com/26213546/86899854-1ce29a80-c13d-11ea-8b63-1c044e425b75.png)

**Comment by ussaema** [comment]
Open the .json SentiCap dataset and you will find an attribute called "split" for each sample indicating its belonging.
![image](https://user-images.githubusercontent.com/37623396/86900989-4e8f3d80-c10c-11ea-91cd-4175fd6ae4e2.png)

**Comment by Doragd** [comment]
In fact, they only used a part of the data (998+673 images in the 2360 images), it seems that they are not divided according to the split attribute in the data set, I think it is difficult to follow their settings.

Well, this is not important, I will use my own training test division.

Thanks again!

**Comment by ussaema** [comment]
That was the reason why I decided to additionally implement the SeqCNNGAN (which uses the same settings as SeqCapsGAN) to evaluate the performance of the capsules.
Welcome and Good Luck ;)

**Comment by Doragd** [comment]
I'm so sorry to bother you again~I have read your paper and found the following statement:
![image](https://user-images.githubusercontent.com/26213546/87010032-912e4400-c1f8-11ea-8cee-a80d112c8d74.png)
**But this seems to be different from the division in the code you provided?** You provide the parameter **senticap_dataset_portions** to divide the data set and set the value to [0.8 0.19 0.01]. This seems to be different from what is stated in the paper?

**Comment by ussaema** [comment]
Yes you are right. We reduced the size of the dataset afterwards to speed up the training time.
